"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UNKNOWN_USER_ID = exports.MESSAGE_SEARCH_SAFE_SCROLL_DELAY = exports.MESSAGE_FOCUS_ANIMATION_DELAY = exports.DEPRECATION_WARNING = exports.DEFAULT_LONG_PRESS_DELAY = void 0;
const DEFAULT_LONG_PRESS_DELAY = 350;
exports.DEFAULT_LONG_PRESS_DELAY = DEFAULT_LONG_PRESS_DELAY;
const MESSAGE_SEARCH_SAFE_SCROLL_DELAY = 500;
exports.MESSAGE_SEARCH_SAFE_SCROLL_DELAY = MESSAGE_SEARCH_SAFE_SCROLL_DELAY;
const MESSAGE_FOCUS_ANIMATION_DELAY = 250;
exports.MESSAGE_FOCUS_ANIMATION_DELAY = MESSAGE_FOCUS_ANIMATION_DELAY;
const DEPRECATION_WARNING = {
  CHANNEL: {
    ON_PRESS_IMAGE_MESSAGE: '`onPressImageMessage` is deprecated, please use `onPressMediaMessage` instead'
  }
};
exports.DEPRECATION_WARNING = DEPRECATION_WARNING;
const UNKNOWN_USER_ID = '##__USER_ID_IS_NOT_PROVIDED__##';
exports.UNKNOWN_USER_ID = UNKNOWN_USER_ID;
//# sourceMappingURL=constants.js.map